# coding: utf-8

"""
    Testing API

    Xyte's Device Cloud is the first all-in-one servitization platform designed for device and hardware manufacturers to cloudify, operate, support, and commercialize their connected devices in a unified platform.   We enable OEMs across different industries to navigate their digital journey, transforming their devices into integrated business solutions that combine hardware, software and services. The only business and commerce platform designed specifically for IoT device manufacturers, our fully-federated Device Cloud empowers OEMs to manage the complete lifecycle of their devices, from the minute they leave the warehouse through aftermarket sales to end customers.  Our out-of-the-box applications for asset management, remote support, ecommerce and subscription management, financing, and a powerful and secure back office suite help OEMs boost revenue and market growth, optimize operational efficiencies, gain instant insights into equipment and device performance, and develop sustainable customer relationships.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from xyte_python_sdk import schemas  # noqa: F401


class DeviceSendChildTelemetries422Response(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def _11303e81_5d56_4910_a472_68676375d995() -> typing.Type['DeviceSendChildTelemetries422Response11303E815D564910A47268676375D995']:
                return DeviceSendChildTelemetries422Response11303E815D564910A47268676375D995
        
            @staticmethod
            def b4adc748_4462_4933_8173_9d40e0a17d22() -> typing.Type['DeviceSendChildTelemetries422ResponseB4Adc7484462493381739D40E0A17D22']:
                return DeviceSendChildTelemetries422ResponseB4Adc7484462493381739D40E0A17D22
            __annotations__ = {
                "11303e81-5d56-4910-a472-68676375d995": _11303e81_5d56_4910_a472_68676375d995,
                "b4adc748-4462-4933-8173-9d40e0a17d22": b4adc748_4462_4933_8173_9d40e0a17d22,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["11303e81-5d56-4910-a472-68676375d995"]) -> 'DeviceSendChildTelemetries422Response11303E815D564910A47268676375D995': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["b4adc748-4462-4933-8173-9d40e0a17d22"]) -> 'DeviceSendChildTelemetries422ResponseB4Adc7484462493381739D40E0A17D22': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["11303e81-5d56-4910-a472-68676375d995", "b4adc748-4462-4933-8173-9d40e0a17d22", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["11303e81-5d56-4910-a472-68676375d995"]) -> typing.Union['DeviceSendChildTelemetries422Response11303E815D564910A47268676375D995', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["b4adc748-4462-4933-8173-9d40e0a17d22"]) -> typing.Union['DeviceSendChildTelemetries422ResponseB4Adc7484462493381739D40E0A17D22', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["11303e81-5d56-4910-a472-68676375d995", "b4adc748-4462-4933-8173-9d40e0a17d22", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DeviceSendChildTelemetries422Response':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
            **kwargs,
        )

from xyte_python_sdk.model.device_send_child_telemetries422_response11303_e815_d564910_a47268676375_d995 import DeviceSendChildTelemetries422Response11303E815D564910A47268676375D995
from xyte_python_sdk.model.device_send_child_telemetries422_response_b4_adc7484462493381739_d40_e0_a17_d22 import DeviceSendChildTelemetries422ResponseB4Adc7484462493381739D40E0A17D22
