# coding: utf-8

"""
    Testing API

    Xyte's Device Cloud is the first all-in-one servitization platform designed for device and hardware manufacturers to cloudify, operate, support, and commercialize their connected devices in a unified platform.   We enable OEMs across different industries to navigate their digital journey, transforming their devices into integrated business solutions that combine hardware, software and services. The only business and commerce platform designed specifically for IoT device manufacturers, our fully-federated Device Cloud empowers OEMs to manage the complete lifecycle of their devices, from the minute they leave the warehouse through aftermarket sales to end customers.  Our out-of-the-box applications for asset management, remote support, ecommerce and subscription management, financing, and a powerful and secure back office suite help OEMs boost revenue and market growth, optimize operational efficiencies, gain instant insights into equipment and device performance, and develop sustainable customer relationships.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from xyte_python_sdk.paths.v1_devices_device_id_dumps_dump_id.put import AppendDumpFileRaw
from xyte_python_sdk.paths.v1_devices_device_id_incidents_incident_id.delete import CloseIncidentRaw
from xyte_python_sdk.paths.v1_devices.post import CreateRegistrationRaw
from xyte_python_sdk.paths.core_v1_partner_devices_device_id.delete import DeleteDeviceRaw
from xyte_python_sdk.paths.core_v1_partner_devices_histories.get import GetAllDeviceStateHistoriesRaw
from xyte_python_sdk.paths.v1_devices_parent_id_children.get import GetChildDevicesRaw
from xyte_python_sdk.paths.v1_devices_device_id_command.get import GetCommandRaw
from xyte_python_sdk.paths.v1_devices_device_id_config.get import GetConfigRaw
from xyte_python_sdk.paths.core_v1_partner_devices_device_id_config.get import GetConfig0Raw
from xyte_python_sdk.paths.v1_devices_device_id_files_file_uuid.get import GetFileRaw
from xyte_python_sdk.paths.v1_devices_device_id_files.get import GetFilesRaw
from xyte_python_sdk.paths.v1_devices_device_id_incidents.get import GetIncidentsRaw
from xyte_python_sdk.paths.v1_devices_device_id.get import GetInfoRaw
from xyte_python_sdk.paths.core_v1_partner_devices_device_id.get import GetInfo0Raw
from xyte_python_sdk.paths.v1_devices_device_id_license.get import GetLicenseRaw
from xyte_python_sdk.paths.v1_devices_device_id_licenses.get import GetLicensesRaw
from xyte_python_sdk.paths.v1_devices_device_id_space.get import GetSpaceInfoRaw
from xyte_python_sdk.paths.core_v1_partner_devices_device_id_history.get import GetStateHistoryRaw
from xyte_python_sdk.paths.core_v1_partner_devices_device_id_telemetries.get import GetTelemetriesRaw
from xyte_python_sdk.paths.core_v1_partner_devices_device_id_commands.get import ListCommandsRaw
from xyte_python_sdk.paths.core_v1_partner_devices.get import ListDevicesRaw
from xyte_python_sdk.paths.v1_devices_device_id_incidents.post import OpenIncidentRaw
from xyte_python_sdk.paths.v1_devices_parent_id_children.post import RegisterChildDeviceRaw
from xyte_python_sdk.paths.v1_devices_device_id_children_telemetries.post import SendChildTelemetriesRaw
from xyte_python_sdk.paths.v1_devices_device_id_command.post import SendCommandRaw
from xyte_python_sdk.paths.v1_devices_device_id_dumps_mime_type_filename.post import SendDumpFileRaw
from xyte_python_sdk.paths.v1_devices_device_id_telemetry.post import SendTelemetryRaw
from xyte_python_sdk.paths.v1_devices_device_id_config.post import SetConfigRaw
from xyte_python_sdk.paths.v1_devices_device_id_cloud_settings.put import UpdateCloudSettingsRaw
from xyte_python_sdk.paths.v1_devices_device_id.put import UpdateDeviceRaw
from xyte_python_sdk.paths.v1_devices_device_id_licenses.post import UpdateLicenseRaw


class DeviceApiRaw(
    AppendDumpFileRaw,
    CloseIncidentRaw,
    CreateRegistrationRaw,
    DeleteDeviceRaw,
    GetAllDeviceStateHistoriesRaw,
    GetChildDevicesRaw,
    GetCommandRaw,
    GetConfigRaw,
    GetConfig0Raw,
    GetFileRaw,
    GetFilesRaw,
    GetIncidentsRaw,
    GetInfoRaw,
    GetInfo0Raw,
    GetLicenseRaw,
    GetLicensesRaw,
    GetSpaceInfoRaw,
    GetStateHistoryRaw,
    GetTelemetriesRaw,
    ListCommandsRaw,
    ListDevicesRaw,
    OpenIncidentRaw,
    RegisterChildDeviceRaw,
    SendChildTelemetriesRaw,
    SendCommandRaw,
    SendDumpFileRaw,
    SendTelemetryRaw,
    SetConfigRaw,
    UpdateCloudSettingsRaw,
    UpdateDeviceRaw,
    UpdateLicenseRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
