# coding: utf-8

"""
    Testing API

    Xyte's Device Cloud is the first all-in-one servitization platform designed for device and hardware manufacturers to cloudify, operate, support, and commercialize their connected devices in a unified platform.   We enable OEMs across different industries to navigate their digital journey, transforming their devices into integrated business solutions that combine hardware, software and services. The only business and commerce platform designed specifically for IoT device manufacturers, our fully-federated Device Cloud empowers OEMs to manage the complete lifecycle of their devices, from the minute they leave the warehouse through aftermarket sales to end customers.  Our out-of-the-box applications for asset management, remote support, ecommerce and subscription management, financing, and a powerful and secure back office suite help OEMs boost revenue and market growth, optimize operational efficiencies, gain instant insights into equipment and device performance, and develop sustainable customer relationships.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from xyte_python_sdk.paths.v1_devices_device_id_dumps_dump_id.put import AppendDumpFile
from xyte_python_sdk.paths.v1_devices_device_id_incidents_incident_id.delete import CloseIncident
from xyte_python_sdk.paths.v1_devices.post import CreateRegistration
from xyte_python_sdk.paths.core_v1_partner_devices_device_id.delete import DeleteDevice
from xyte_python_sdk.paths.core_v1_partner_devices_histories.get import GetAllDeviceStateHistories
from xyte_python_sdk.paths.v1_devices_parent_id_children.get import GetChildDevices
from xyte_python_sdk.paths.v1_devices_device_id_command.get import GetCommand
from xyte_python_sdk.paths.v1_devices_device_id_config.get import GetConfig
from xyte_python_sdk.paths.core_v1_partner_devices_device_id_config.get import GetConfig0
from xyte_python_sdk.paths.v1_devices_device_id_files_file_uuid.get import GetFile
from xyte_python_sdk.paths.v1_devices_device_id_files.get import GetFiles
from xyte_python_sdk.paths.v1_devices_device_id_incidents.get import GetIncidents
from xyte_python_sdk.paths.v1_devices_device_id.get import GetInfo
from xyte_python_sdk.paths.core_v1_partner_devices_device_id.get import GetInfo0
from xyte_python_sdk.paths.v1_devices_device_id_license.get import GetLicense
from xyte_python_sdk.paths.v1_devices_device_id_licenses.get import GetLicenses
from xyte_python_sdk.paths.v1_devices_device_id_space.get import GetSpaceInfo
from xyte_python_sdk.paths.core_v1_partner_devices_device_id_history.get import GetStateHistory
from xyte_python_sdk.paths.core_v1_partner_devices_device_id_telemetries.get import GetTelemetries
from xyte_python_sdk.paths.core_v1_partner_devices_device_id_commands.get import ListCommands
from xyte_python_sdk.paths.core_v1_partner_devices.get import ListDevices
from xyte_python_sdk.paths.v1_devices_device_id_incidents.post import OpenIncident
from xyte_python_sdk.paths.v1_devices_parent_id_children.post import RegisterChildDevice
from xyte_python_sdk.paths.v1_devices_device_id_children_telemetries.post import SendChildTelemetries
from xyte_python_sdk.paths.v1_devices_device_id_command.post import SendCommand
from xyte_python_sdk.paths.v1_devices_device_id_dumps_mime_type_filename.post import SendDumpFile
from xyte_python_sdk.paths.v1_devices_device_id_telemetry.post import SendTelemetry
from xyte_python_sdk.paths.v1_devices_device_id_config.post import SetConfig
from xyte_python_sdk.paths.v1_devices_device_id_cloud_settings.put import UpdateCloudSettings
from xyte_python_sdk.paths.v1_devices_device_id.put import UpdateDevice
from xyte_python_sdk.paths.v1_devices_device_id_licenses.post import UpdateLicense
from xyte_python_sdk.apis.tags.device_api_raw import DeviceApiRaw


class DeviceApi(
    AppendDumpFile,
    CloseIncident,
    CreateRegistration,
    DeleteDevice,
    GetAllDeviceStateHistories,
    GetChildDevices,
    GetCommand,
    GetConfig,
    GetConfig0,
    GetFile,
    GetFiles,
    GetIncidents,
    GetInfo,
    GetInfo0,
    GetLicense,
    GetLicenses,
    GetSpaceInfo,
    GetStateHistory,
    GetTelemetries,
    ListCommands,
    ListDevices,
    OpenIncident,
    RegisterChildDevice,
    SendChildTelemetries,
    SendCommand,
    SendDumpFile,
    SendTelemetry,
    SetConfig,
    UpdateCloudSettings,
    UpdateDevice,
    UpdateLicense,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DeviceApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DeviceApiRaw(api_client)
