# coding: utf-8

"""
    Testing API

    Xyte's Device Cloud is the first all-in-one servitization platform designed for device and hardware manufacturers to cloudify, operate, support, and commercialize their connected devices in a unified platform.   We enable OEMs across different industries to navigate their digital journey, transforming their devices into integrated business solutions that combine hardware, software and services. The only business and commerce platform designed specifically for IoT device manufacturers, our fully-federated Device Cloud empowers OEMs to manage the complete lifecycle of their devices, from the minute they leave the warehouse through aftermarket sales to end customers.  Our out-of-the-box applications for asset management, remote support, ecommerce and subscription management, financing, and a powerful and secure back office suite help OEMs boost revenue and market growth, optimize operational efficiencies, gain instant insights into equipment and device performance, and develop sustainable customer relationships.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from xyte_python_sdk.pydantic.device_get_info_response_config import DeviceGetInfoResponseConfig
from xyte_python_sdk.pydantic.device_get_info_response_custom import DeviceGetInfoResponseCustom
from xyte_python_sdk.pydantic.device_get_info_response_partner import DeviceGetInfoResponsePartner
from xyte_python_sdk.pydantic.device_get_info_response_state import DeviceGetInfoResponseState

class DeviceGetInfoResponse(BaseModel):
    id: typing.Optional[str] = Field(None, alias='id')

    partner: typing.Optional[DeviceGetInfoResponsePartner] = Field(None, alias='partner')

    config: typing.Optional[DeviceGetInfoResponseConfig] = Field(None, alias='config')

    state: typing.Optional[DeviceGetInfoResponseState] = Field(None, alias='state')

    last_seen: typing.Optional[str] = Field(None, alias='last_seen')

    custom: typing.Optional[DeviceGetInfoResponseCustom] = Field(None, alias='custom')

    name: typing.Optional[str] = Field(None, alias='name')

    firmware_version: typing.Optional[str] = Field(None, alias='firmware_version')

    claimed: typing.Optional[str] = Field(None, alias='claimed')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
