# coding: utf-8

"""
    Testing API

    Xyte's Device Cloud is the first all-in-one servitization platform designed for device and hardware manufacturers to cloudify, operate, support, and commercialize their connected devices in a unified platform.   We enable OEMs across different industries to navigate their digital journey, transforming their devices into integrated business solutions that combine hardware, software and services. The only business and commerce platform designed specifically for IoT device manufacturers, our fully-federated Device Cloud empowers OEMs to manage the complete lifecycle of their devices, from the minute they leave the warehouse through aftermarket sales to end customers.  Our out-of-the-box applications for asset management, remote support, ecommerce and subscription management, financing, and a powerful and secure back office suite help OEMs boost revenue and market growth, optimize operational efficiencies, gain instant insights into equipment and device performance, and develop sustainable customer relationships.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class DeviceCreateRegistrationRequest(BaseModel):
    # Unique device serial number
    sn: str = Field(alias='sn')

    # Semver based firmware version
    firmware_version: str = Field(alias='firmware_version')

    # Key defined in the model's hardware key section
    hardware_key: str = Field(alias='hardware_key')

    # MAC address of the device
    mac: typing.Optional[str] = Field(None, alias='mac')

    # Unique device identifier (must specify this or mac)
    cloud_id: typing.Optional[str] = Field(None, alias='cloud_id')

    # Display name for the end-user
    name: typing.Optional[str] = Field(None, alias='name')

    # Generic JSON object with unconstrained data
    details: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='details')

    # Additional model details text
    sub_model: typing.Optional[str] = Field(None, alias='sub_model')

    # UUID of the parent device
    parent_id: typing.Optional[str] = Field(None, alias='parent_id')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
