# coding: utf-8

"""
    Testing API

    Xyte's Device Cloud is the first all-in-one servitization platform designed for device and hardware manufacturers to cloudify, operate, support, and commercialize their connected devices in a unified platform.   We enable OEMs across different industries to navigate their digital journey, transforming their devices into integrated business solutions that combine hardware, software and services. The only business and commerce platform designed specifically for IoT device manufacturers, our fully-federated Device Cloud empowers OEMs to manage the complete lifecycle of their devices, from the minute they leave the warehouse through aftermarket sales to end customers.  Our out-of-the-box applications for asset management, remote support, ecommerce and subscription management, financing, and a powerful and secure back office suite help OEMs boost revenue and market growth, optimize operational efficiencies, gain instant insights into equipment and device performance, and develop sustainable customer relationships.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from xyte_python_sdk.pydantic.device_send_child_telemetries_response11303_e815_d564910_a47268676375_d995 import DeviceSendChildTelemetriesResponse11303E815D564910A47268676375D995
from xyte_python_sdk.pydantic.device_send_child_telemetries_response_b4_adc7484462493381739_d40_e0_a17_d22 import DeviceSendChildTelemetriesResponseB4Adc7484462493381739D40E0A17D22

class DeviceSendChildTelemetriesResponse(BaseModel):
    11303e81-5d56-4910-a472-68676375d995_: typing.Optional[DeviceSendChildTelemetriesResponse11303E815D564910A47268676375D995] = Field(None, alias='11303e81-5d56-4910-a472-68676375d995')

    b4adc748-4462-4933-8173-9d40e0a17d22_: typing.Optional[DeviceSendChildTelemetriesResponseB4Adc7484462493381739D40E0A17D22] = Field(None, alias='b4adc748-4462-4933-8173-9d40e0a17d22')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
