# coding: utf-8
"""
    Testing API

    Xyte's Device Cloud is the first all-in-one servitization platform designed for device and hardware manufacturers to cloudify, operate, support, and commercialize their connected devices in a unified platform.   We enable OEMs across different industries to navigate their digital journey, transforming their devices into integrated business solutions that combine hardware, software and services. The only business and commerce platform designed specifically for IoT device manufacturers, our fully-federated Device Cloud empowers OEMs to manage the complete lifecycle of their devices, from the minute they leave the warehouse through aftermarket sales to end customers.  Our out-of-the-box applications for asset management, remote support, ecommerce and subscription management, financing, and a powerful and secure back office suite help OEMs boost revenue and market growth, optimize operational efficiencies, gain instant insights into equipment and device performance, and develop sustainable customer relationships.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from xyte_python_sdk.client_custom import ClientCustom
from xyte_python_sdk.configuration import Configuration
from xyte_python_sdk.api_client import ApiClient
from xyte_python_sdk.type_util import copy_signature
from xyte_python_sdk.apis.tags.device_api import DeviceApi
from xyte_python_sdk.apis.tags.ticket_api import TicketApi



class Xyte(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.device: DeviceApi = DeviceApi(api_client)
        self.ticket: TicketApi = TicketApi(api_client)
