# coding: utf-8

"""
    Testing API

    Xyte's Device Cloud is the first all-in-one servitization platform designed for device and hardware manufacturers to cloudify, operate, support, and commercialize their connected devices in a unified platform.   We enable OEMs across different industries to navigate their digital journey, transforming their devices into integrated business solutions that combine hardware, software and services. The only business and commerce platform designed specifically for IoT device manufacturers, our fully-federated Device Cloud empowers OEMs to manage the complete lifecycle of their devices, from the minute they leave the warehouse through aftermarket sales to end customers.  Our out-of-the-box applications for asset management, remote support, ecommerce and subscription management, financing, and a powerful and secure back office suite help OEMs boost revenue and market growth, optimize operational efficiencies, gain instant insights into equipment and device performance, and develop sustainable customer relationships.

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDeviceUpdateDeviceResponseState(TypedDict):
    pass

class OptionalDeviceUpdateDeviceResponseState(TypedDict, total=False):
    temp: int

    status: str

    eco_mode: bool

    presence: bool

    temp_dir: int

    data_rate: int

    coffee_used: int

    power_status: bool

    ambient_light: int

    data_rate_dir: int

    motion_sensor: bool

    coffee_used_dir: int

    ambient_light_dir: int

class DeviceUpdateDeviceResponseState(RequiredDeviceUpdateDeviceResponseState, OptionalDeviceUpdateDeviceResponseState):
    pass
